##
## ATOS PROJECT 2022
## MAKEFILE
## File description:
## Wow, such make, much file!
##

SLURM_INC_DIR = /root/SLURM/slurm.build
DEMETER_LIB_DIR = /home/atos/demeter/lib_demeter
DEMETER_RUN_PATH = /shared/